Get some random numbers for Aussie Powerball lotto
viet-aus-it/vait-discord-bot pull request #128
Opened 2022-10-13 01:22 UTC by jkiller295

If you want to have a chance at winning the Powerball, try the numbers suggested by our bot.

2022-10-17 05:25 UTC, jkiller295 commented
@dohaicuong @samhwang cho xin 2c review

2022-10-26 20:23 UTC, samhwang requested changes

2022-10-26 20:23 UTC, samhwang commented on src/commands/powerball/index.ts
> +    .reduce((array: number[]) => {
Cái này làm đơn giản trong 1 cái reduce thôi, đừng .reduce.map

Also powerball có xếp đúng thứ tự từ thấp tới cao ko? Nếu không thì cũngk cần sort, gom được cái .join vô cái .reduce luôn.

2022-10-26 20:23 UTC, samhwang commented on src/commands/powerball/index.ts
> +    .fill(undefined)
như trên

2022-10-27 03:38 UTC, jkiller295 commented on src/commands/powerball/index.ts
> +    .reduce((array: number[]) => {
> Cái này làm đơn giản trong 1 cái reduce thôi, đừng .reduce.map
> 
> Also powerball có xếp đúng thứ tự từ thấp tới cao ko? Nếu không thì cũngk cần sort, gom được cái .join vô cái .reduce luôn.

Hình như đâu có được tại cái method `getUniqueRandomIntInclusive` lấy `number[]`

2022-10-27 04:13 UTC, samhwang approved these changes

2022-10-27 04:14 UTC, merged