Cowsay Function
viet-aus-it/vait-discord-bot pull request #54
Opened 2021-05-31 12:31 UTC by NNCT2904

## Description

## Motivation and Context

## Related Issue

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-06 11:02 UTC, samhwang requested changes

2021-06-07 01:35 UTC, samhwang commented on discord-bot/src/commands/cowsay/index.ts
> +const sendCowsay = async (string: string, channel: any) => {
@NNCT2904 em tạo 1 cái `const textChannel = channel as TextChannel` r sau đó mấy cái sau mà cần textChannel thì cứ pass cái const này vào thôi, k cần import hết mấy type DMChannel đâu vì bot của mình k send private message

vd:

```ts
const textChannel = channel as TextChannel;

// ...
  // If cowsay is called with chat content
  if (!isBlank(chatContent)) {
    sendCowsay(chatContent, textChannel);
    return;
  }
```

2021-06-12 01:07 UTC, jkiller295 approved these changes

2021-06-12 04:57 UTC, NNCT2904 commented on discord-bot/src/commands/cowsay/index.ts
> +const sendCowsay = async (string: string, channel: any) => {
Done!

2021-06-13 22:00 UTC, samhwang approved these changes

2021-06-13 22:00 UTC, merged